# Generated by Django 5.1.4 on 2025-01-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="title",
            field=models.CharField(default="", max_length=25),
        ),
    ]
