# Generated by Django 5.1.4 on 2025-01-13 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_feedback_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="uploads/videos/")),
                ("location_longitude", models.CharField(max_length=100)),
                ("location_latitude", models.CharField(max_length=100)),
                ("uploaded_date", models.DateField(auto_now_add=True)),
                ("uploaded_time", models.TimeField(auto_now=True)),
                ("processed_frames_path", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
